// Generated by CoffeeScript 1.4.0
(function() {
  var FuzzyMatch;

  try {
    FuzzyMatch = require("./fuzzyMatch");
  } catch (e) {
    FuzzyMatch = window.FuzzyMatch;
  }

  this.don = new FuzzyMatch("Don Quixote", "Don Juan Castro", "Don Padre", "Don Quijote", "James Bond");

  console.log(this.don.rank());

}).call(this);
